name: 'check reminders'

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@v1
